name: TournamentsPlugin
version: '${project.version}'
main: com.github.gavvydizzle.tournamentsplugin.TournamentsPlugin
api-version: 1.18
depend: [ServerUtils]
softdepend: [GangsPlugin, PlaceholderAPI, PrisonEnchants, ShopGUIPlus]
authors: [GavvyDizzle]
description: Individual and Gangs tournament plugin for Spigot
commands:
  tournadmin:
    description: TournamentPlugin admin commands
    permission: tournamentsplugin.admin
  tourn:
    aliases: [tournament, tournaments]
    description: TournamentPlugin player commands
    permission: tournamentsplugin.menu
